# Generated by Django 3.0.5 on 2020-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=5000)),
                ('origPrice', models.BigIntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('sizeCm', models.BigIntegerField(default=0)),
                ('type', models.CharField(default='', max_length=500)),
                ('material', models.CharField(default='', max_length=50000)),
                ('stock', models.BigIntegerField(default=0)),
                ('availabilty', models.BooleanField(default=True)),
                ('details', models.CharField(default='', max_length=50000)),
                ('color', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
