# Generated by Django 3.0.5 on 2020-07-22 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
    ]
