# Generated by Django 3.0.5 on 2020-08-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200731_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user',
        ),
    ]
