# Generated by Django 3.0.5 on 2020-08-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200731_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
