# Generated by Django 3.0.5 on 2020-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200805_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
    ]
