# Generated by Django 3.0.5 on 2020-08-08 08:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availabilty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeCm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='origPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ProductSizeStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('sizeCm', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(default='', max_length=500)),
                ('pics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
    ]
