# Generated by Django 3.0.5 on 2020-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='pics',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
