# Generated by Django 3.0.5 on 2020-08-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200813_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='pics',
            field=models.ImageField(default='', upload_to='polls/'),
        ),
    ]
