# Generated by Django 3.0.5 on 2020-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200813_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='pics',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
