# Generated by Django 3.0.5 on 2020-08-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200813_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorimage',
            name='pics',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='img/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ProductColorImage')),
            ],
        ),
    ]
