# Generated by Django 3.0.5 on 2020-08-14 07:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20200813_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50000), size=None),
        ),
    ]
