# Generated by Django 3.0.5 on 2020-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200817_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courierPartner',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='trackingId',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
