# Generated by Django 3.0.5 on 2020-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
