# Generated by Django 3.0.5 on 2020-08-30 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20200830_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(null=True, to='polls.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
    ]
