# Generated by Django 3.0.5 on 2020-08-30 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200830_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), null=True, size=None),
        ),
    ]
