# Generated by Django 3.0.5 on 2020-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20200831_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='polls.Product'),
        ),
    ]
