# Generated by Django 3.0.5 on 2020-08-31 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20200831_0021'),
    ]

    operations = [

        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
    ]
